# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oldurosi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/16 16:14:07 by oldurosi          #+#    #+#              #
#    Updated: 2019/09/16 16:44:04 by oldurosi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

IDIR	= ../libft
GCC	= gcc
CFLAGS	= -Wall -Wextra -Werror
AR	= ar rc
RANLIB = ranlib

NAME	= 
HEAD	=
SRCS	=

OBJS	=

.PHONY:
